### PR TITLE
Added Channel Override to Message Posts

### PR DESCRIPTION
**Pull request by adamfisher**
Slack provides the ability to specify an override for the channel you post into other than the default one specified when you setup the web hook. This PR exposes the channel property.

### CODE REVIEW

**Comment by adamfisher** [comment]
That integration test was failing before I modified anything. I didn't bother with it but I did add a unit test for the new channel property.

**Comment by micdah** [comment]
Hi @adamfisher,

Thanks for your great submission - everything looks fine, so I will merge it.
The failing integration test is due to AppVeyor not allowing the build to access secure variables, in which the webhook url is held to run that particular test - so it should probably work just fine when it runs from master.

Have you tested it out with changing channel, I find the documentation is conflicting with itself from Slack:
Here https://api.slack.com/incoming-webhooks they note:
> You cannot override the default username, icon, or channel for incoming webhooks attached to Slack apps. Instead, these values will stubbornly inherit from the associated Slack app configuration.

But then on this page https://api.slack.com/custom-integrations/incoming-webhooks they note
> Incoming webhooks output to a default channel and can only send messages to a single channel at a time. You can override a custom integration's configured channel by specifying the channel field in your JSON payload.

So it is quite difficult to ascertain whether they allow it or not 😄

**Comment by micdah** [comment]
I just made a quick integration test, which verified that your addition worked - by setting `channel` it in fact allows sending to different channel than the one configured in the webhook URL. 😄 

So excellent work.

**Comment by micdah** [comment]
1.0.22 has been released to nuget.org with your changes

**Comment by adamfisher** [comment]
👍

**Pull request merged**
